
spring:
  mvc:
    hiddenmethod.filter.enabled=true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB10Dialect
    hibernate.ddl-auto: create
    show_sql: true

  datasource:
    url: jdbc:mariadb://localhost:3307/mystudy
    username: root
    password: Dksrbstmd122719!
    driver-class-name: org.mariadb.jdbc.Driver



